In [ ]:
import pandas
import numpy
merged_dataframe = pandas.read_csv("merged_stocks_and_twitter_sentiment.csv")
merged_dataframe

Date       Open       High        Low      Close  Adj Close  \
0    2016-01-04  25.652500  26.342501  25.500000  26.337500  24.364536   
1    2016-01-05  26.437500  26.462500  25.602501  25.677500  23.753977   
2    2016-01-06  25.139999  25.592501  24.967501  25.174999  23.289116   
3    2016-01-07  24.670000  25.032499  24.107500  24.112499  22.306208   
4    2016-01-08  24.637501  24.777500  24.190001  24.240000  22.424154   
..          ...        ...        ...        ...        ...        ...   
916  2019-08-23  52.357498  53.012501  50.250000  50.660000  50.001186   
917  2019-08-26  51.465000  51.797501  51.264999  51.622501  50.951172   
918  2019-08-27  51.965000  52.137501  50.882500  51.040001  50.376244   
919  2019-08-28  51.025002  51.430000  50.830002  51.382500  50.714291   
920  2019-08-29  52.125000  52.330002  51.665001  52.252499  51.572975   

        Volume  ts_polarity  twitter_volume  
0    270597600     0.070389            1133  
1    223164000     0.133635            1430  
2    273829600     0.072042            1949  
3    324377600     0.074369            2289  
4    283192000     0.051595            2235  
..         ...          ...             ...  
916  187272000     0.097330            1103  
917  104174400     0.072340             888  
918  103493200     0.117541             962  
919   63755200     0.061477             895  
920   83962000     0.056460            1083  

[921 rows x 9 columns]

In [ ]:
dataframe = merged_dataframe[["Date", "Adj Close","Volume","ts_polarity","twitter_volume"]]
dataframe

Date  Adj Close     Volume  ts_polarity  twitter_volume
0    2016-01-04  24.364536  270597600     0.070389            1133
1    2016-01-05  23.753977  223164000     0.133635            1430
2    2016-01-06  23.289116  273829600     0.072042            1949
3    2016-01-07  22.306208  324377600     0.074369            2289
4    2016-01-08  22.424154  283192000     0.051595            2235
..          ...        ...        ...          ...             ...
916  2019-08-23  50.001186  187272000     0.097330            1103
917  2019-08-26  50.951172  104174400     0.072340             888
918  2019-08-27  50.376244  103493200     0.117541             962
919  2019-08-28  50.714291   63755200     0.061477             895
920  2019-08-29  51.572975   83962000     0.056460            1083

[921 rows x 5 columns]

In [ ]:
dataframe.set_index("Date", inplace = True)
dataframe

Adj Close     Volume  ts_polarity  twitter_volume
Date                                                         
2016-01-04  24.364536  270597600     0.070389            1133
2016-01-05  23.753977  223164000     0.133635            1430
2016-01-06  23.289116  273829600     0.072042            1949
2016-01-07  22.306208  324377600     0.074369            2289
2016-01-08  22.424154  283192000     0.051595            2235
...               ...        ...          ...             ...
2019-08-23  50.001186  187272000     0.097330            1103
2019-08-26  50.951172  104174400     0.072340             888
2019-08-27  50.376244  103493200     0.117541             962
2019-08-28  50.714291   63755200     0.061477             895
2019-08-29  51.572975   83962000     0.056460            1083

[921 rows x 4 columns]

In [ ]:
POSITIVE_SENTIMENT_THRESHOLD = 0.05
NEGATIVE_SENTIMENT_THRESHOLD = -0.05
sentiments = []
for sentiment_score in dataframe["ts_polarity"]:
  if sentiment_score >= POSITIVE_SENTIMENT_THRESHOLD:
    sentiments.append("Positive")
  elif sentiment_score <= NEGATIVE_SENTIMENT_THRESHOLD:
    sentiments.append("Negative")
  else:
    sentiments.append("Neutral")

In [ ]:
dataframe["Sentiment"] = sentiments
dataframe

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Adj Close     Volume  ts_polarity  twitter_volume Sentiment
Date                                                                   
2016-01-04  24.364536  270597600     0.070389            1133  Positive
2016-01-05  23.753977  223164000     0.133635            1430  Positive
2016-01-06  23.289116  273829600     0.072042            1949  Positive
2016-01-07  22.306208  324377600     0.074369            2289  Positive
2016-01-08  22.424154  283192000     0.051595            2235  Positive
...               ...        ...          ...             ...       ...
2019-08-23  50.001186  187272000     0.097330            1103  Positive
2019-08-26  50.951172  104174400     0.072340             888  Positive
2019-08-27  50.376244  103493200     0.117541             962  Positive
2019-08-28  50.714291   63755200     0.061477             895  Positive
2019-08-29  51.572975   83962000     0.056460            1083  Positive

[921 rows x 5 columns]

In [ ]:
dataframe["Sentiment"].value_counts()
dataframe["Adj Close"].value_counts()
dataframe["Price Difference"] = dataframe["Adj Close"].diff()
dataframe.dropna(inplace = True)
dataframe

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


Adj Close     Volume  ts_polarity  twitter_volume Sentiment  \
Date                                                                      
2016-01-05  23.753977  223164000     0.133635            1430  Positive   
2016-01-06  23.289116  273829600     0.072042            1949  Positive   
2016-01-07  22.306208  324377600     0.074369            2289  Positive   
2016-01-08  22.424154  283192000     0.051595            2235  Positive   
2016-01-11  22.787258  198957600     0.019443            1222   Neutral   
...               ...        ...          ...             ...       ...   
2019-08-23  50.001186  187272000     0.097330            1103  Positive   
2019-08-26  50.951172  104174400     0.072340             888  Positive   
2019-08-27  50.376244  103493200     0.117541             962  Positive   
2019-08-28  50.714291   63755200     0.061477             895  Positive   
2019-08-29  51.572975   83962000     0.056460            1083  Positive   

            Price Difference  
Date                          
2016-01-05         -0.610559  
2016-01-06         -0.464861  
2016-01-07         -0.982908  
2016-01-08          0.117946  
2016-01-11          0.363104  
...                      ...  
2019-08-23         -2.423077  
2019-08-26          0.949986  
2019-08-27         -0.574928  
2019-08-28          0.338047  
2019-08-29          0.858684  

[920 rows x 6 columns]

In [ ]:
RISE = 1
FALL = 0
dataframe["Stock Trend"] = numpy.where(
    dataframe["Price Difference"] > 0, RISE, FALL
)
dataframe

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


Adj Close     Volume  ts_polarity  twitter_volume Sentiment  \
Date                                                                      
2016-01-05  23.753977  223164000     0.133635            1430  Positive   
2016-01-06  23.289116  273829600     0.072042            1949  Positive   
2016-01-07  22.306208  324377600     0.074369            2289  Positive   
2016-01-08  22.424154  283192000     0.051595            2235  Positive   
2016-01-11  22.787258  198957600     0.019443            1222   Neutral   
...               ...        ...          ...             ...       ...   
2019-08-23  50.001186  187272000     0.097330            1103  Positive   
2019-08-26  50.951172  104174400     0.072340             888  Positive   
2019-08-27  50.376244  103493200     0.117541             962  Positive   
2019-08-28  50.714291   63755200     0.061477             895  Positive   
2019-08-29  51.572975   83962000     0.056460            1083  Positive   

            Price Difference  Stock Trend  
Date                                       
2016-01-05         -0.610559            0  
2016-01-06         -0.464861            0  
2016-01-07         -0.982908            0  
2016-01-08          0.117946            1  
2016-01-11          0.363104            1  
...                      ...          ...  
2019-08-23         -2.423077            0  
2019-08-26          0.949986            1  
2019-08-27         -0.574928            0  
2019-08-28          0.338047            1  
2019-08-29          0.858684            1  

[920 rows x 7 columns]

In [ ]:
new_dataframe = dataframe[["Adj Close","Volume","twitter_volume","Sentiment","Stock Trend"]]
new_dataframe = pandas.get_dummies(new_dataframe, columns = ["Sentiment"])
new_dataframe

Adj Close     Volume  twitter_volume  Stock Trend  \
Date                                                            
2016-01-05  23.753977  223164000            1430            0   
2016-01-06  23.289116  273829600            1949            0   
2016-01-07  22.306208  324377600            2289            0   
2016-01-08  22.424154  283192000            2235            1   
2016-01-11  22.787258  198957600            1222            1   
...               ...        ...             ...          ...   
2019-08-23  50.001186  187272000            1103            0   
2019-08-26  50.951172  104174400             888            1   
2019-08-27  50.376244  103493200             962            0   
2019-08-28  50.714291   63755200             895            1   
2019-08-29  51.572975   83962000            1083            1   

            Sentiment_Negative  Sentiment_Neutral  Sentiment_Positive  
Date                                                                   
2016-01-05                   0                  0                   1  
2016-01-06                   0                  0                   1  
2016-01-07                   0                  0                   1  
2016-01-08                   0                  0                   1  
2016-01-11                   0                  1                   0  
...                        ...                ...                 ...  
2019-08-23                   0                  0                   1  
2019-08-26                   0                  0                   1  
2019-08-27                   0                  0                   1  
2019-08-28                   0                  0                   1  
2019-08-29                   0                  0                   1  

[920 rows x 7 columns]

In [ ]:
X = new_dataframe.copy()
X.drop("Stock Trend", axis = 1, inplace = True)
X

Adj Close     Volume  twitter_volume  Sentiment_Negative  \
Date                                                                   
2016-01-05  23.753977  223164000            1430                   0   
2016-01-06  23.289116  273829600            1949                   0   
2016-01-07  22.306208  324377600            2289                   0   
2016-01-08  22.424154  283192000            2235                   0   
2016-01-11  22.787258  198957600            1222                   0   
...               ...        ...             ...                 ...   
2019-08-23  50.001186  187272000            1103                   0   
2019-08-26  50.951172  104174400             888                   0   
2019-08-27  50.376244  103493200             962                   0   
2019-08-28  50.714291   63755200             895                   0   
2019-08-29  51.572975   83962000            1083                   0   

            Sentiment_Neutral  Sentiment_Positive  
Date                                               
2016-01-05                  0                   1  
2016-01-06                  0                   1  
2016-01-07                  0                   1  
2016-01-08                  0                   1  
2016-01-11                  1                   0  
...                       ...                 ...  
2019-08-23                  0                   1  
2019-08-26                  0                   1  
2019-08-27                  0                   1  
2019-08-28                  0                   1  
2019-08-29                  0                   1  

[920 rows x 6 columns]

In [ ]:
y = new_dataframe["Stock Trend"].values.reshape(-1, 1)
y[:10]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled  = X_scaler.transform(X_test)
X_test_scaled

array([[-0.38091803, -0.84634224, -0.57527246, -0.06397476, -0.42365927,
         0.43033148],
       [ 1.49351771,  0.28164428,  0.38385447, -0.06397476,  2.36038738,
        -2.32379001],
       [-0.422598  , -1.04855936, -1.3964517 , -0.06397476, -0.42365927,
         0.43033148],
       ...,
       [-0.06317119, -0.01019666, -0.45814706, -0.06397476, -0.42365927,
         0.43033148],
       [-1.51926932,  3.35399478,  1.47312074, -0.06397476, -0.42365927,
         0.43033148],
       [ 0.05165723, -0.35668171, -0.49458607, -0.06397476, -0.42365927,
         0.43033148]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
NUMBER_OF_ESTIMATORS = 500
RANDOM_STATE = 80
classifier = RandomForestClassifier(n_estimators = NUMBER_OF_ESTIMATORS,random_state = RANDOM_STATE)
classifier = classifier.fit(X_train_scaled,y_train.ravel())
classifier

RandomForestClassifier(n_estimators=500, random_state=80)

In [ ]:
predictions = classifier.predict(X_test_scaled)
predictions

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
pandas.DataFrame({
    "Prediction": predictions,
    "Actual": y_test.ravel()
})

Prediction  Actual
0             0       0
1             0       1
2             0       1
3             1       1
4             1       1
..          ...     ...
179           1       1
180           0       0
181           0       0
182           0       0
183           0       0

[184 rows x 2 columns]

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)
print(accuracy)

0.5652173913043478


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.45      0.56      0.50        72
           1       0.67      0.57      0.62       112

    accuracy                           0.57       184
   macro avg       0.56      0.56      0.56       184
weighted avg       0.58      0.57      0.57       184



In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix_results = confusion_matrix(y_test,predictions)

In [ ]:
confusion_matrix_results

array([[40, 32],
       [48, 64]])

In [ ]:
confusion_matrix_dataframe = pandas.DataFrame(confusion_matrix_results,index = ["Actual 0","Actual 1"],columns = ["Predicted 0", "Predicted 1"])
display(confusion_matrix_dataframe)

Predicted 0  Predicted 1
Actual 0           40           32
Actual 1           48           64

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1, 1.5, 2]
NUMBER_OF_ESTIMATORS  = 30
MAX_NUMBER_OF_FEATURES = 2
MAX_DEPTH = 3
RANDOM_STATE_CONSTANT = 0
for learning_rate in learning_rates:
  classifier = GradientBoostingClassifier(n_estimators  = NUMBER_OF_ESTIMATORS,
                                          learning_rate = learning_rate,
                                          max_features  = MAX_NUMBER_OF_FEATURES,
                                          max_depth     = MAX_DEPTH,
                                          random_state  = RANDOM_STATE_CONSTANT)
  classifier.fit(X_train_scaled,y_train.ravel())
  training_score = classifier.score(X_train_scaled, y_train.ravel())
  testing_score  = classifier.score(X_test_scaled, y_test.ravel())

In [ ]:
LEARNING_RATE = 1
MAXIMUM_NUMBER_OF_FEATURES = 5
classifier = GradientBoostingClassifier(n_estimators  = NUMBER_OF_ESTIMATORS,
                                        learning_rate = LEARNING_RATE,
                                        max_features  = MAXIMUM_NUMBER_OF_FEATURES,
                                        max_depth     = MAX_DEPTH,
                                        random_state  = RANDOM_STATE_CONSTANT)
classifier.fit(X_train_scaled, y_train.ravel())
training_score = classifier.score(X_train_scaled, y_train)
testing_score  = classifier.score(X_test_scaled, y_test)
print("Training Score: ", training_score)

Training Score:  0.8967391304347826
